name       : findbugs          # name of the package
version    : 3.0.1-1           # version of the package
kind       : tool              # one of tool or spec(s)
description: A program which uses static analysis to look for bugs in Java code.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com

assets:
    - asset   : MAIN
      name    : Findbugs Distribution (3.0.1)
      url     : http://iweb.dl.sourceforge.net/project/findbugs/findbugs/3.0.1/findbugs-3.0.1.zip
      platform: all
        
# assumes:
#   - cmd: java --version # right now just support cmd -- maybe file exists?
#     contains: 1.7
#     message: "Sorry, but this package requires Java, version 1.7 or higher."


install:
  - cmd: unzip MAIN
    description: Unpacking FindBugs Distribution...
    platform: all
